spring.datasource.url=jdbc:mysql://13.235.133.204:3306/shipment_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=supplychain
spring.datasource.password=Supply@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
